# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/puzzlebox_jigsaw_interface_design-plugin_bloom.ui'
#
# Created: Wed Mar 25 16:24:36 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
#Form.resize()
		#self.horizontalLayoutWidget = QtGui.QWidget(Form)
		self.horizontalLayoutWidget = QtGui.QWidget()
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1719, 857))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem)
		self.webViewBloom = QtWebKit.QWebView(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.webViewBloom.sizePolicy().hasHeightForWidth())
		self.webViewBloom.setSizePolicy(sizePolicy)
		self.webViewBloom.setObjectName("webViewBloom")
		self.horizontalLayout.addWidget(self.webViewBloom)
		spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem1)
		self.verticalLayout_4 = QtGui.QVBoxLayout()
		self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.horizontalLayout_4 = QtGui.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem2)
		self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label_4.setObjectName("label_4")
		self.horizontalLayout_4.addWidget(self.label_4)
		spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem3)
		self.verticalLayout_4.addLayout(self.horizontalLayout_4)
		self.widgetPlotRawEEG = QtGui.QWidget(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widgetPlotRawEEG.sizePolicy().hasHeightForWidth())
		self.widgetPlotRawEEG.setSizePolicy(sizePolicy)
		self.widgetPlotRawEEG.setMinimumSize(QtCore.QSize(520, 160))
		self.widgetPlotRawEEG.setObjectName("widgetPlotRawEEG")
		self.labelMockupRawEEG = QtGui.QLabel(self.widgetPlotRawEEG)
		self.labelMockupRawEEG.setGeometry(QtCore.QRect(0, 0, 520, 160))
		self.labelMockupRawEEG.setText("")
		self.labelMockupRawEEG.setPixmap(QtGui.QPixmap("images/mockup-raw_eeg_waves.png"))
		self.labelMockupRawEEG.setObjectName("labelMockupRawEEG")
		self.verticalLayout_4.addWidget(self.widgetPlotRawEEG)
		self.horizontalLayoutBloomControl = QtGui.QHBoxLayout()
		self.horizontalLayoutBloomControl.setObjectName("horizontalLayoutBloomControl")
		spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutBloomControl.addItem(spacerItem4)
		self.labelBloomControl = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomControl.setObjectName("labelBloomControl")
		self.horizontalLayoutBloomControl.addWidget(self.labelBloomControl)
		spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutBloomControl.addItem(spacerItem5)
		self.verticalLayout_4.addLayout(self.horizontalLayoutBloomControl)
		self.horizontalLayoutFlightPlan = QtGui.QHBoxLayout()
		self.horizontalLayoutFlightPlan.setObjectName("horizontalLayoutFlightPlan")
		self.verticalLayoutBloomControl = QtGui.QVBoxLayout()
		self.verticalLayoutBloomControl.setObjectName("verticalLayoutBloomControl")
		self.gridLayoutBloomControl = QtGui.QGridLayout()
		self.gridLayoutBloomControl.setObjectName("gridLayoutBloomControl")
		self.pushButtonBloomClose = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonBloomClose.setEnabled(True)
		self.pushButtonBloomClose.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonBloomClose.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonBloomClose.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("images/bloom-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonBloomClose.setIcon(icon)
		self.pushButtonBloomClose.setIconSize(QtCore.QSize(40, 40))
		self.pushButtonBloomClose.setCheckable(True)
		self.pushButtonBloomClose.setChecked(False)
		self.pushButtonBloomClose.setObjectName("pushButtonBloomClose")
		self.gridLayoutBloomControl.addWidget(self.pushButtonBloomClose, 2, 0, 1, 1)
		self.labelBloomCycle = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomCycle.setMidLineWidth(0)
		self.labelBloomCycle.setTextFormat(QtCore.Qt.AutoText)
		self.labelBloomCycle.setAlignment(QtCore.Qt.AlignCenter)
		self.labelBloomCycle.setObjectName("labelBloomCycle")
		self.gridLayoutBloomControl.addWidget(self.labelBloomCycle, 0, 2, 1, 1)
		self.pushButtonBloomCycle = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonBloomCycle.setEnabled(True)
		self.pushButtonBloomCycle.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonBloomCycle.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonBloomCycle.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("images/bloom-cycle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonBloomCycle.setIcon(icon1)
		self.pushButtonBloomCycle.setIconSize(QtCore.QSize(40, 40))
		self.pushButtonBloomCycle.setCheckable(True)
		self.pushButtonBloomCycle.setChecked(False)
		self.pushButtonBloomCycle.setObjectName("pushButtonBloomCycle")
		self.gridLayoutBloomControl.addWidget(self.pushButtonBloomCycle, 2, 2, 1, 1)
		self.labelBloomClose = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomClose.setMidLineWidth(0)
		self.labelBloomClose.setTextFormat(QtCore.Qt.AutoText)
		self.labelBloomClose.setAlignment(QtCore.Qt.AlignCenter)
		self.labelBloomClose.setObjectName("labelBloomClose")
		self.gridLayoutBloomControl.addWidget(self.labelBloomClose, 0, 0, 1, 1)
		self.pushButtonBloomOpen = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonBloomOpen.setEnabled(True)
		self.pushButtonBloomOpen.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonBloomOpen.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonBloomOpen.setText("")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("images/bloom-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonBloomOpen.setIcon(icon2)
		self.pushButtonBloomOpen.setIconSize(QtCore.QSize(50, 50))
		self.pushButtonBloomOpen.setCheckable(True)
		self.pushButtonBloomOpen.setObjectName("pushButtonBloomOpen")
		self.gridLayoutBloomControl.addWidget(self.pushButtonBloomOpen, 2, 1, 1, 1)
		self.labelBloomOpen = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomOpen.setMidLineWidth(0)
		self.labelBloomOpen.setTextFormat(QtCore.Qt.AutoText)
		self.labelBloomOpen.setAlignment(QtCore.Qt.AlignCenter)
		self.labelBloomOpen.setObjectName("labelBloomOpen")
		self.gridLayoutBloomControl.addWidget(self.labelBloomOpen, 0, 1, 1, 1)
		self.pushButtonBloomDemo = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonBloomDemo.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonBloomDemo.setText("")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("images/bloom-demo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonBloomDemo.setIcon(icon3)
		self.pushButtonBloomDemo.setIconSize(QtCore.QSize(40, 40))
		self.pushButtonBloomDemo.setCheckable(True)
		self.pushButtonBloomDemo.setObjectName("pushButtonBloomDemo")
		self.gridLayoutBloomControl.addWidget(self.pushButtonBloomDemo, 2, 3, 1, 1)
		self.labelBloomDemo = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomDemo.setAlignment(QtCore.Qt.AlignCenter)
		self.labelBloomDemo.setObjectName("labelBloomDemo")
		self.gridLayoutBloomControl.addWidget(self.labelBloomDemo, 0, 3, 1, 1)
		self.verticalLayoutBloomControl.addLayout(self.gridLayoutBloomControl)
		self.horizontalLayoutPosition = QtGui.QHBoxLayout()
		self.horizontalLayoutPosition.setObjectName("horizontalLayoutPosition")
		spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutPosition.addItem(spacerItem6)
		self.labelPosition = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelPosition.setObjectName("labelPosition")
		self.horizontalLayoutPosition.addWidget(self.labelPosition)
		spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutPosition.addItem(spacerItem7)
		self.verticalLayoutBloomControl.addLayout(self.horizontalLayoutPosition)
		self.horizontalSliderBloomPosition = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderBloomPosition.setEnabled(True)
		self.horizontalSliderBloomPosition.setMaximum(100)
		self.horizontalSliderBloomPosition.setPageStep(2)
		self.horizontalSliderBloomPosition.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderBloomPosition.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderBloomPosition.setTickInterval(10)
		self.horizontalSliderBloomPosition.setObjectName("horizontalSliderBloomPosition")
		self.verticalLayoutBloomControl.addWidget(self.horizontalSliderBloomPosition)
		spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutBloomControl.addItem(spacerItem8)
		self.horizontalLayoutFlightPlan.addLayout(self.verticalLayoutBloomControl)
		self.verticalLayoutRGB = QtGui.QVBoxLayout()
		self.verticalLayoutRGB.setObjectName("verticalLayoutRGB")
		self.horizontalLayoutBloomRed = QtGui.QHBoxLayout()
		self.horizontalLayoutBloomRed.setObjectName("horizontalLayoutBloomRed")
		spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutBloomRed.addItem(spacerItem9)
		self.labelBloomRed = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomRed.setTextFormat(QtCore.Qt.PlainText)
		self.labelBloomRed.setObjectName("labelBloomRed")
		self.horizontalLayoutBloomRed.addWidget(self.labelBloomRed)
		spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutBloomRed.addItem(spacerItem10)
		self.verticalLayoutRGB.addLayout(self.horizontalLayoutBloomRed)
		self.horizontalSliderBloomRed = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderBloomRed.setEnabled(True)
		self.horizontalSliderBloomRed.setMaximum(255)
		self.horizontalSliderBloomRed.setPageStep(2)
		self.horizontalSliderBloomRed.setProperty("value", 0)
		self.horizontalSliderBloomRed.setSliderPosition(0)
		self.horizontalSliderBloomRed.setTracking(True)
		self.horizontalSliderBloomRed.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderBloomRed.setInvertedAppearance(False)
		self.horizontalSliderBloomRed.setInvertedControls(False)
		self.horizontalSliderBloomRed.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderBloomRed.setTickInterval(10)
		self.horizontalSliderBloomRed.setObjectName("horizontalSliderBloomRed")
		self.verticalLayoutRGB.addWidget(self.horizontalSliderBloomRed)
		self.horizontalLayoutBloomGreen = QtGui.QHBoxLayout()
		self.horizontalLayoutBloomGreen.setObjectName("horizontalLayoutBloomGreen")
		spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutBloomGreen.addItem(spacerItem11)
		self.labelBloomGreen = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomGreen.setTextFormat(QtCore.Qt.PlainText)
		self.labelBloomGreen.setObjectName("labelBloomGreen")
		self.horizontalLayoutBloomGreen.addWidget(self.labelBloomGreen)
		spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutBloomGreen.addItem(spacerItem12)
		self.verticalLayoutRGB.addLayout(self.horizontalLayoutBloomGreen)
		self.horizontalSliderBloomGreen = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderBloomGreen.setEnabled(True)
		self.horizontalSliderBloomGreen.setMaximum(255)
		self.horizontalSliderBloomGreen.setPageStep(2)
		self.horizontalSliderBloomGreen.setProperty("value", 0)
		self.horizontalSliderBloomGreen.setSliderPosition(0)
		self.horizontalSliderBloomGreen.setTracking(True)
		self.horizontalSliderBloomGreen.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderBloomGreen.setInvertedAppearance(False)
		self.horizontalSliderBloomGreen.setInvertedControls(False)
		self.horizontalSliderBloomGreen.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderBloomGreen.setTickInterval(10)
		self.horizontalSliderBloomGreen.setObjectName("horizontalSliderBloomGreen")
		self.verticalLayoutRGB.addWidget(self.horizontalSliderBloomGreen)
		self.horizontalLayoutBloomBlue = QtGui.QHBoxLayout()
		self.horizontalLayoutBloomBlue.setObjectName("horizontalLayoutBloomBlue")
		spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutBloomBlue.addItem(spacerItem13)
		self.labelBloomBlue = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomBlue.setTextFormat(QtCore.Qt.PlainText)
		self.labelBloomBlue.setObjectName("labelBloomBlue")
		self.horizontalLayoutBloomBlue.addWidget(self.labelBloomBlue)
		spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutBloomBlue.addItem(spacerItem14)
		self.verticalLayoutRGB.addLayout(self.horizontalLayoutBloomBlue)
		self.horizontalSliderBloomBlue = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderBloomBlue.setEnabled(True)
		self.horizontalSliderBloomBlue.setMaximum(255)
		self.horizontalSliderBloomBlue.setPageStep(2)
		self.horizontalSliderBloomBlue.setProperty("value", 0)
		self.horizontalSliderBloomBlue.setSliderPosition(0)
		self.horizontalSliderBloomBlue.setTracking(True)
		self.horizontalSliderBloomBlue.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderBloomBlue.setInvertedAppearance(False)
		self.horizontalSliderBloomBlue.setInvertedControls(False)
		self.horizontalSliderBloomBlue.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderBloomBlue.setTickInterval(10)
		self.horizontalSliderBloomBlue.setObjectName("horizontalSliderBloomBlue")
		self.verticalLayoutRGB.addWidget(self.horizontalSliderBloomBlue)
		spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutRGB.addItem(spacerItem15)
		self.horizontalLayoutFlightPlan.addLayout(self.verticalLayoutRGB)
		self.verticalLayout_4.addLayout(self.horizontalLayoutFlightPlan)
		self.horizontalLayout_6 = QtGui.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_6.addItem(spacerItem16)
		self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label_6.setTextFormat(QtCore.Qt.AutoText)
		self.label_6.setObjectName("label_6")
		self.horizontalLayout_6.addWidget(self.label_6)
		spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_6.addItem(spacerItem17)
		self.verticalLayout_4.addLayout(self.horizontalLayout_6)
		self.widgetPlotHistory = QtGui.QWidget(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widgetPlotHistory.sizePolicy().hasHeightForWidth())
		self.widgetPlotHistory.setSizePolicy(sizePolicy)
		self.widgetPlotHistory.setMinimumSize(QtCore.QSize(520, 160))
		self.widgetPlotHistory.setObjectName("widgetPlotHistory")
		self.labelMockupHistory = QtGui.QLabel(self.widgetPlotHistory)
		self.labelMockupHistory.setGeometry(QtCore.QRect(0, 0, 520, 160))
		self.labelMockupHistory.setText("")
		self.labelMockupHistory.setPixmap(QtGui.QPixmap("images/mockup-esense_values_history.jpg"))
		self.labelMockupHistory.setScaledContents(True)
		self.labelMockupHistory.setObjectName("labelMockupHistory")
		self.verticalLayout_4.addWidget(self.widgetPlotHistory)
		spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayout_4.addItem(spacerItem18)
		self.horizontalLayout.addLayout(self.verticalLayout_4)
		spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem19)
		self.verticalLayoutSessionProfile = QtGui.QVBoxLayout()
		self.verticalLayoutSessionProfile.setObjectName("verticalLayoutSessionProfile")
		spacerItem20 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutSessionProfile.addItem(spacerItem20)
		self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label_2.setObjectName("label_2")
		self.verticalLayoutSessionProfile.addWidget(self.label_2)
		self.horizontalLayout_8 = QtGui.QHBoxLayout()
		self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.textLabelBloomConcentration = QtGui.QLabel(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelBloomConcentration.sizePolicy().hasHeightForWidth())
		self.textLabelBloomConcentration.setSizePolicy(sizePolicy)
		self.textLabelBloomConcentration.setWordWrap(False)
		self.textLabelBloomConcentration.setObjectName("textLabelBloomConcentration")
		self.horizontalLayout_8.addWidget(self.textLabelBloomConcentration)
		spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_8.addItem(spacerItem21)
		self.pushButtonBloomConcentrationEnable = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonBloomConcentrationEnable.setEnabled(False)
		self.pushButtonBloomConcentrationEnable.setCheckable(True)
		self.pushButtonBloomConcentrationEnable.setChecked(True)
		self.pushButtonBloomConcentrationEnable.setObjectName("pushButtonBloomConcentrationEnable")
		self.horizontalLayout_8.addWidget(self.pushButtonBloomConcentrationEnable)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_8)
		self.progressBarBloomConcentration = QtGui.QProgressBar(self.horizontalLayoutWidget)
		self.progressBarBloomConcentration.setEnabled(True)
		self.progressBarBloomConcentration.setMinimumSize(QtCore.QSize(0, 60))
		self.progressBarBloomConcentration.setProperty("value", 0)
		self.progressBarBloomConcentration.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarBloomConcentration.setObjectName("progressBarBloomConcentration")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarBloomConcentration)
		self.horizontalSliderBloomConcentration = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderBloomConcentration.setEnabled(True)
		self.horizontalSliderBloomConcentration.setMaximum(100)
		self.horizontalSliderBloomConcentration.setPageStep(2)
		self.horizontalSliderBloomConcentration.setProperty("value", 72)
		self.horizontalSliderBloomConcentration.setSliderPosition(72)
		self.horizontalSliderBloomConcentration.setTracking(True)
		self.horizontalSliderBloomConcentration.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderBloomConcentration.setInvertedAppearance(False)
		self.horizontalSliderBloomConcentration.setInvertedControls(False)
		self.horizontalSliderBloomConcentration.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderBloomConcentration.setTickInterval(10)
		self.horizontalSliderBloomConcentration.setObjectName("horizontalSliderBloomConcentration")
		self.verticalLayoutSessionProfile.addWidget(self.horizontalSliderBloomConcentration)
		self.horizontalLayout_9 = QtGui.QHBoxLayout()
		self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		self.textLabelBloomRelaxation = QtGui.QLabel(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelBloomRelaxation.sizePolicy().hasHeightForWidth())
		self.textLabelBloomRelaxation.setSizePolicy(sizePolicy)
		self.textLabelBloomRelaxation.setWordWrap(False)
		self.textLabelBloomRelaxation.setObjectName("textLabelBloomRelaxation")
		self.horizontalLayout_9.addWidget(self.textLabelBloomRelaxation)
		spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_9.addItem(spacerItem22)
		self.pushButtonBloomRelaxationEnable = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonBloomRelaxationEnable.setEnabled(False)
		self.pushButtonBloomRelaxationEnable.setCheckable(True)
		self.pushButtonBloomRelaxationEnable.setChecked(True)
		self.pushButtonBloomRelaxationEnable.setObjectName("pushButtonBloomRelaxationEnable")
		self.horizontalLayout_9.addWidget(self.pushButtonBloomRelaxationEnable)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_9)
		self.progressBarBloomRelaxation = QtGui.QProgressBar(self.horizontalLayoutWidget)
		self.progressBarBloomRelaxation.setEnabled(True)
		self.progressBarBloomRelaxation.setMinimumSize(QtCore.QSize(0, 60))
		self.progressBarBloomRelaxation.setProperty("value", 0)
		self.progressBarBloomRelaxation.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarBloomRelaxation.setObjectName("progressBarBloomRelaxation")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarBloomRelaxation)
		self.horizontalSliderBloomRelaxation = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderBloomRelaxation.setEnabled(True)
		self.horizontalSliderBloomRelaxation.setMaximum(100)
		self.horizontalSliderBloomRelaxation.setPageStep(2)
		self.horizontalSliderBloomRelaxation.setProperty("value", 0)
		self.horizontalSliderBloomRelaxation.setSliderPosition(0)
		self.horizontalSliderBloomRelaxation.setTracking(True)
		self.horizontalSliderBloomRelaxation.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderBloomRelaxation.setInvertedAppearance(False)
		self.horizontalSliderBloomRelaxation.setInvertedControls(False)
		self.horizontalSliderBloomRelaxation.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderBloomRelaxation.setTickInterval(10)
		self.horizontalSliderBloomRelaxation.setObjectName("horizontalSliderBloomRelaxation")
		self.verticalLayoutSessionProfile.addWidget(self.horizontalSliderBloomRelaxation)
		self.horizontalLayout_10 = QtGui.QHBoxLayout()
		self.horizontalLayout_10.setObjectName("horizontalLayout_10")
		self.textLabelBloomConnectionLevel = QtGui.QLabel(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelBloomConnectionLevel.sizePolicy().hasHeightForWidth())
		self.textLabelBloomConnectionLevel.setSizePolicy(sizePolicy)
		self.textLabelBloomConnectionLevel.setWordWrap(False)
		self.textLabelBloomConnectionLevel.setObjectName("textLabelBloomConnectionLevel")
		self.horizontalLayout_10.addWidget(self.textLabelBloomConnectionLevel)
		spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_10.addItem(spacerItem23)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_10)
		self.progressBarBloomConnectionLevel = QtGui.QProgressBar(self.horizontalLayoutWidget)
		self.progressBarBloomConnectionLevel.setEnabled(True)
		self.progressBarBloomConnectionLevel.setProperty("value", 0)
		self.progressBarBloomConnectionLevel.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarBloomConnectionLevel.setObjectName("progressBarBloomConnectionLevel")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarBloomConnectionLevel)
		self.horizontalLayout_11 = QtGui.QHBoxLayout()
		self.horizontalLayout_11.setObjectName("horizontalLayout_11")
		self.textLabelBloomConnectionLevel_2 = QtGui.QLabel(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelBloomConnectionLevel_2.sizePolicy().hasHeightForWidth())
		self.textLabelBloomConnectionLevel_2.setSizePolicy(sizePolicy)
		self.textLabelBloomConnectionLevel_2.setWordWrap(False)
		self.textLabelBloomConnectionLevel_2.setObjectName("textLabelBloomConnectionLevel_2")
		self.horizontalLayout_11.addWidget(self.textLabelBloomConnectionLevel_2)
		spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_11.addItem(spacerItem24)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_11)
		self.progressBarBloomPower = QtGui.QProgressBar(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.progressBarBloomPower.sizePolicy().hasHeightForWidth())
		self.progressBarBloomPower.setSizePolicy(sizePolicy)
		self.progressBarBloomPower.setMinimumSize(QtCore.QSize(100, 0))
		self.progressBarBloomPower.setProperty("value", 65)
		self.progressBarBloomPower.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarBloomPower.setObjectName("progressBarBloomPower")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarBloomPower)
		spacerItem25 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutSessionProfile.addItem(spacerItem25)
		self.labelBloomControlModule = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelBloomControlModule.setEnabled(True)
		self.labelBloomControlModule.setAlignment(QtCore.Qt.AlignCenter)
		self.labelBloomControlModule.setObjectName("labelBloomControlModule")
		self.verticalLayoutSessionProfile.addWidget(self.labelBloomControlModule)
		self.textLabelBloomStatus = QtGui.QLabel(self.horizontalLayoutWidget)
		self.textLabelBloomStatus.setEnabled(True)
		self.textLabelBloomStatus.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelBloomStatus.setWordWrap(False)
		self.textLabelBloomStatus.setObjectName("textLabelBloomStatus")
		self.verticalLayoutSessionProfile.addWidget(self.textLabelBloomStatus)
		self.textLabelBloomHardwareSelection = QtGui.QLabel(self.horizontalLayoutWidget)
		self.textLabelBloomHardwareSelection.setEnabled(True)
		self.textLabelBloomHardwareSelection.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelBloomHardwareSelection.setWordWrap(False)
		self.textLabelBloomHardwareSelection.setObjectName("textLabelBloomHardwareSelection")
		self.verticalLayoutSessionProfile.addWidget(self.textLabelBloomHardwareSelection)
		self.comboBoxBloomModelName = QtGui.QComboBox(self.horizontalLayoutWidget)
		self.comboBoxBloomModelName.setEnabled(True)
		self.comboBoxBloomModelName.setObjectName("comboBoxBloomModelName")
		self.comboBoxBloomModelName.addItem("")
		self.verticalLayoutSessionProfile.addWidget(self.comboBoxBloomModelName)
		self.comboBoxBloomPortSelect = QtGui.QComboBox(self.horizontalLayoutWidget)
		self.comboBoxBloomPortSelect.setEnabled(True)
		self.comboBoxBloomPortSelect.setObjectName("comboBoxBloomPortSelect")
		self.comboBoxBloomPortSelect.addItem("")
		self.verticalLayoutSessionProfile.addWidget(self.comboBoxBloomPortSelect)
		self.horizontalLayoutSessionButtons_2 = QtGui.QHBoxLayout()
		self.horizontalLayoutSessionButtons_2.setObjectName("horizontalLayoutSessionButtons_2")
		self.pushButtonBloomConnect = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonBloomConnect.setEnabled(True)
		self.pushButtonBloomConnect.setCheckable(True)
		self.pushButtonBloomConnect.setObjectName("pushButtonBloomConnect")
		self.horizontalLayoutSessionButtons_2.addWidget(self.pushButtonBloomConnect)
		self.pushButtonBloomSearch = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonBloomSearch.setCheckable(False)
		self.pushButtonBloomSearch.setObjectName("pushButtonBloomSearch")
		self.horizontalLayoutSessionButtons_2.addWidget(self.pushButtonBloomSearch)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayoutSessionButtons_2)
		spacerItem26 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutSessionProfile.addItem(spacerItem26)
		self.horizontalLayout.addLayout(self.verticalLayoutSessionProfile)
		spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem27)

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		Form.setWindowTitle(QtGui.QApplication.translate("Form", "Puzzlebox Jigsaw - Plug-in - Bloom", None, QtGui.QApplication.UnicodeUTF8))
		self.label_4.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Raw EEG Waves</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomControl.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Control</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomCycle.setText(QtGui.QApplication.translate("Form", "Cycle", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomClose.setText(QtGui.QApplication.translate("Form", "Close", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomOpen.setText(QtGui.QApplication.translate("Form", "Open", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomDemo.setText(QtGui.QApplication.translate("Form", "Demo", None, QtGui.QApplication.UnicodeUTF8))
		self.labelPosition.setText(QtGui.QApplication.translate("Form", "Position", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomRed.setText(QtGui.QApplication.translate("Form", "Red", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomGreen.setText(QtGui.QApplication.translate("Form", "Green", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomBlue.setText(QtGui.QApplication.translate("Form", "Blue", None, QtGui.QApplication.UnicodeUTF8))
		self.label_6.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Brain Signals History</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.label_2.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Current Data</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelBloomConcentration.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Concentration</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonBloomConcentrationEnable.setToolTip(QtGui.QApplication.translate("Form", "enable/disable concentration processing", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonBloomConcentrationEnable.setText(QtGui.QApplication.translate("Form", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelBloomRelaxation.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Relaxation</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonBloomRelaxationEnable.setToolTip(QtGui.QApplication.translate("Form", "enable/disable relaxation processing", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonBloomRelaxationEnable.setText(QtGui.QApplication.translate("Form", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelBloomConnectionLevel.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ground/Reference Signal</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelBloomConnectionLevel_2.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt;\">Bloom Growth Rate</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelBloomControlModule.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.Helvetica Neue DeskInterface\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Bloom Interface Module</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelBloomStatus.setText(QtGui.QApplication.translate("Form", "<p align=\"center\">Status: Disconnected</p>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelBloomHardwareSelection.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hardware Selection</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxBloomModelName.setItemText(0, QtGui.QApplication.translate("Form", "Puzzlebox Bloom", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxBloomPortSelect.setItemText(0, QtGui.QApplication.translate("Form", "Select Port", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonBloomConnect.setText(QtGui.QApplication.translate("Form", "Connect", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonBloomSearch.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
